#!/usr/bin/env python3
"""Nightly chaos: random fault injection from the spec/scenarios vocabulary, every language pair.

    python3 tools/chaos.py --seeds 5 [--r-src r]

For each seed a scenario is generated (random backpressure, transient 503/500, dropped responses,
tunnel-restart 404s, post-ACK redeliveries, delivery delays), written under a temp dir, and the
matrix is run in CONF_MODE=chaos. Acceptable outcomes: every round completes, or a round times
out and the peer stays usable, or a leg ends with a typed terminal error. Anything else (a crash,
a hang, a non-typed error) fails the run. Seeds are printed so a failure can be replayed.
"""

from __future__ import annotations

import argparse
import json
import random
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))

import matrix  # noqa: E402


def generate(seed: int, rounds: int) -> dict[str, object]:
    rng = random.Random(seed)

    def pick(k: int) -> list[int]:
        return sorted(rng.sample(range(1, rounds * 2 + 1), k))

    faults: dict[str, object] = {}
    if rng.random() < 0.7:
        faults["backpressureOnRequest"] = pick(rng.randint(1, 2))
    if rng.random() < 0.5:
        faults["backpressureOnRespond"] = pick(1)
    if rng.random() < 0.5:
        faults["notReadyOnRequest"] = pick(1)
    if rng.random() < 0.5:
        faults["serverErrorOnRequest"] = pick(1)
    if rng.random() < 0.6:
        faults["dropResponseRounds"] = sorted(rng.sample(range(1, rounds + 1), 1))
    if rng.random() < 0.6:
        faults["forgetCorrelationRounds"] = sorted(rng.sample(range(1, rounds + 1), 1))
    if rng.random() < 0.6:
        faults["redeliverAfterAckRounds"] = sorted(rng.sample(range(1, rounds + 1), 1))
    if rng.random() < 0.4:
        faults["delayDeliveryMs"] = {str(rng.randint(1, rounds)): rng.choice([500, 1500, 3000])}
    return {
        "id": f"chaos-{seed}",
        "description": f"generated by tools/chaos.py seed={seed}",
        "legs": [{"legId": "leg-a", "peerOrgSlug": "dp-a"}],
        "longpollMs": 300,
        "redeliveryMs": rng.choice([1000, 3000]),
        "faults": faults,
    }


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--seeds", type=int, default=3)
    ap.add_argument("--seed", type=int, default=None, help="replay a single seed")
    ap.add_argument("--rounds", type=int, default=4)
    ap.add_argument("--pairs", nargs="*", default=None)
    ap.add_argument("--r-src", default=None)
    ap.add_argument("--rscript", default="Rscript")
    ap.add_argument("--py-installed", action="store_true")
    args = ap.parse_args(argv)
    seeds = (
        [args.seed] if args.seed is not None else [random.SystemRandom().randrange(1, 10**6) for _ in range(args.seeds)]
    )
    failures = 0
    with tempfile.TemporaryDirectory() as tmp:
        for seed in seeds:
            sc = generate(seed, args.rounds)
            path = Path(tmp) / f"{sc['id']}.json"
            path.write_text(json.dumps(sc, indent=2))
            print(f"=== seed {seed}: faults {json.dumps(sc['faults'])}", flush=True)
            argv_m = [
                "--scenario",
                str(path),
                "--rounds",
                str(args.rounds),
                "--chaos",
                "--no-hub",
                "--rscript",
                args.rscript,
                "--timeout",
                "300",
            ]
            if args.pairs:
                argv_m += ["--pairs", *args.pairs]
            if args.r_src:
                argv_m += ["--r-src", args.r_src]
            if args.py_installed:
                argv_m += ["--py-installed"]
            if matrix.main(argv_m) != 0:
                failures += 1
                print(
                    f"!!! seed {seed} failed; replay with: python3 tools/chaos.py --seed {seed} --rounds {args.rounds}",
                    flush=True,
                )
    print(f"\nchaos: {len(seeds) - failures}/{len(seeds)} seeds ok")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
