#!/usr/bin/env Rscript
# Emit a single-directory drop of safeinsights.fusion for source()-style vendoring (ADR 0003 fallback):
#
#   Rscript r/vendor.R <out-dir>
#
# The drop is `safeinsights.fusion.R` (a loader) plus a `safeinsights.fusion/` directory holding every R/*.R file. The
# loader sources them into an environment named `safeinsights.fusion` and attaches it, so researcher code can
# call `safeinsights.fusion::fusion_connect()`-style functions as `fusion_connect()` after `source("safeinsights.fusion.R")`.
# The package files live in their own directory so they never collide with researcher files of the
# same name (the SDK has a `source.R`; so does many a study). Only `curl` and `jsonlite` are needed.

args <- commandArgs(trailingOnly = TRUE)
if (length(args) != 1) stop("usage: Rscript r/vendor.R <out-dir>")
out <- args[[1]]
pkg <- normalizePath(file.path(dirname(sub("--file=", "", grep("--file=", commandArgs(), value = TRUE)[1])), "."), mustWork = TRUE)
r_dir <- file.path(pkg, "R")
pkg_out <- file.path(out, "safeinsights.fusion")
dir.create(pkg_out, recursive = TRUE, showWarnings = FALSE)
files <- sort(list.files(r_dir, pattern = "\\.R$", full.names = TRUE))
for (f in files) file.copy(f, file.path(pkg_out, basename(f)), overwrite = TRUE)
desc <- read.dcf(file.path(pkg, "DESCRIPTION"))
version <- desc[1, "Version"]
loader <- c(
  "# safeinsights.fusion vendored drop - generated by r/vendor.R; do not edit.",
  sprintf("# Version %s. Requires: curl, jsonlite.", version),
  "local({",
  "  here <- dirname(normalizePath(sys.frame(1)$ofile %||% (function() { f <- grep('--file=', commandArgs(), value = TRUE); if (length(f)) sub('--file=', '', f[1]) else 'safeinsights.fusion.R' })(), mustWork = FALSE))",
  "  env <- new.env(parent = globalenv())",
  sprintf("  for (f in c(%s)) sys.source(file.path(here, \"safeinsights.fusion\", f), envir = env)", paste(sprintf("\"%s\"", basename(files)), collapse = ", ")),
  sprintf("  env$.safeinsights_fusion_vendored_version <- \"%s\"", version),
  "  env$.fusion_log$level <- 20L",
  "  if ('safeinsights.fusion' %in% search()) detach('safeinsights.fusion', character.only = TRUE)",
  "  attach(env, name = 'safeinsights.fusion', warn.conflicts = FALSE)",
  "})",
  "`%||%` <- function(a, b) if (is.null(a)) b else a"
)
# `%||%` must exist before the block runs: put it first.
loader <- c(loader[1:2], "`%||%` <- function(a, b) if (is.null(a)) b else a", loader[3:(length(loader) - 1)])
writeLines(loader, file.path(out, "safeinsights.fusion.R"))
cat(sprintf("vendored safeinsights.fusion %s: safeinsights.fusion.R + %d files in safeinsights.fusion/ into %s\n", version, length(files), out))
